version: "3.7"

services:
  postgresdb:
    build:
      context: ./database
    restart: always
    environment:
      - POSTGRES_USER=DeveloperUser
      - POSTGRES_PASSWORD=DogThatBarkDoesntBite
      - POSTGRES_DB=StoreManagerDB
    ports:
      - "7800:5432"


  app:
    restart: always
    build:
      context: ./StoreManager/src
    depends_on:
      - postgresdb
    ports:
      - "7802:80"